# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crypterMot.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 300)
        Dialog.setMinimumSize(QtCore.QSize(320, 300))
        Dialog.setMaximumSize(QtCore.QSize(320, 300))
        Dialog.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 258, 256))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setStyleSheet("border: none;\n"
"background-color: rgb(206, 92, 0);\n"
"color:white;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Crypter mot"))
        self.pushButton.setText(_translate("Dialog", "Crypter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
