# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(280, 280))
        MainWindow.setMaximumSize(QtCore.QSize(280, 280))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 227, 217))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font-size:16px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.cryptStr = QtWidgets.QPushButton(self.layoutWidget)
        self.cryptStr.setStyleSheet("border: none;\n"
"padding: 10px;\n"
"background-color: rgb(252, 175, 62);\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;")
        self.cryptStr.setObjectName("cryptStr")
        self.verticalLayout.addWidget(self.cryptStr)
        self.decryptStr = QtWidgets.QPushButton(self.layoutWidget)
        self.decryptStr.setStyleSheet("border: none;\n"
"padding: 10px;\n"
"background-color: rgb(138, 226, 52);\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;")
        self.decryptStr.setObjectName("decryptStr")
        self.verticalLayout.addWidget(self.decryptStr)
        self.cryptFile = QtWidgets.QPushButton(self.layoutWidget)
        self.cryptFile.setStyleSheet("background-color: #1fa3ec;\n"
"border: none;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;")
        self.cryptFile.setObjectName("cryptFile")
        self.verticalLayout.addWidget(self.cryptFile)
        self.decryptFile = QtWidgets.QPushButton(self.layoutWidget)
        self.decryptFile.setStyleSheet("border: none;\n"
"background-color: rgb(186, 189, 182);\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"margin: 2px 20px;\n"
"border-radius: 10px;")
        self.decryptFile.setObjectName("decryptFile")
        self.verticalLayout.addWidget(self.decryptFile)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cryptage Décryptage"))
        self.label.setText(_translate("MainWindow", "Veuillez choisir une option"))
        self.cryptStr.setText(_translate("MainWindow", "Crypter mot"))
        self.decryptStr.setText(_translate("MainWindow", "Décrypter mot"))
        self.cryptFile.setText(_translate("MainWindow", "Crypter fichier texte"))
        self.decryptFile.setText(_translate("MainWindow", "Décrypter fichier texte"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
